# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Z...
tagline:             ''
description:         ''
url:                 http://xiongzh.com
baseurl:             'http://xiongzh.com'
paginate:            5

# About/contact
author:
  name:              Zhen XIONG
  url:               https://weibo.com/dreamcatcherpo
  email:             837075787@qq.com

# Custom vars
version:             1.0.0
